"""Pure-data coverage for authenticator_common: json helpers, Authentication,
state setter, expiration, and refreshed-token JWT handling.
"""

import json
import unittest
from datetime import datetime, timedelta, timezone
from unittest.mock import MagicMock

import jwt

from yalexs.authenticator_common import (
    Authentication,
    AuthenticationState,
    AuthenticatorCommon,
    from_authentication_json,
    to_authentication_json,
)
from yalexs.const import (
    DEFAULT_BRAND,
    HEADER_ACCESS_TOKEN,
    HEADER_AUGUST_ACCESS_TOKEN,
)


def _fmt(dt: datetime) -> str:
    return dt.strftime("%Y-%m-%dT%H:%M:%S.%fZ")


class TestJsonHelpers(unittest.TestCase):
    def test_to_authentication_json_with_none(self):
        self.assertEqual("{}", to_authentication_json(None))

    def test_from_authentication_json_with_none(self):
        self.assertIsNone(from_authentication_json(None))

    def test_roundtrip(self):
        expires_at = _fmt(datetime.now(timezone.utc) + timedelta(days=10))
        original = Authentication(
            AuthenticationState.AUTHENTICATED,
            install_id="iid",
            access_token="tok",
            access_token_expires=expires_at,
        )
        revived = from_authentication_json(json.loads(to_authentication_json(original)))
        self.assertEqual(original.install_id, revived.install_id)
        self.assertEqual(original.access_token, revived.access_token)
        self.assertEqual(original.access_token_expires, revived.access_token_expires)
        self.assertEqual(original.state, revived.state)


class TestAuthentication(unittest.TestCase):
    def test_install_id_autogenerated_when_missing(self):
        auth = Authentication(AuthenticationState.REQUIRES_AUTHENTICATION)
        self.assertTrue(auth.install_id)
        self.assertNotEqual("", auth.install_id)

    def test_state_setter(self):
        auth = Authentication(AuthenticationState.REQUIRES_AUTHENTICATION)
        auth.state = AuthenticationState.AUTHENTICATED
        self.assertEqual(AuthenticationState.AUTHENTICATED, auth.state)

    def test_is_expired_true_for_past(self):
        expires_at = _fmt(datetime.now(timezone.utc) - timedelta(days=1))
        auth = Authentication(
            AuthenticationState.AUTHENTICATED, access_token_expires=expires_at
        )
        self.assertTrue(auth.is_expired())

    def test_is_expired_false_for_future(self):
        expires_at = _fmt(datetime.now(timezone.utc) + timedelta(days=1))
        auth = Authentication(
            AuthenticationState.AUTHENTICATED, access_token_expires=expires_at
        )
        self.assertFalse(auth.is_expired())

    def test_parsed_expiration_time_none_when_no_expires(self):
        auth = Authentication(AuthenticationState.REQUIRES_AUTHENTICATION)
        self.assertIsNone(auth.parsed_expiration_time())


class TestAuthenticatorCommon(unittest.TestCase):
    def _build(self) -> AuthenticatorCommon:
        api = MagicMock()
        api.brand = DEFAULT_BRAND
        common = AuthenticatorCommon(api, "phone", "user", "pass", install_id="iid")
        common._authentication = Authentication(
            AuthenticationState.AUTHENTICATED,
            install_id="iid",
            access_token="old_token",
            access_token_expires=_fmt(
                datetime.now(timezone.utc) + timedelta(days=30)
            ),
        )
        return common

    def test_session_response_prefers_access_token_header_over_august(self):
        common = self._build()
        result = common._authentication_from_session_response(
            "iid",
            {HEADER_ACCESS_TOKEN: "new", HEADER_AUGUST_ACCESS_TOKEN: "old"},
            {
                "expiresAt": _fmt(datetime.now(timezone.utc) + timedelta(days=1)),
                "vPassword": True,
                "vInstallId": True,
            },
        )
        self.assertEqual("new", result.access_token)
        self.assertEqual(AuthenticationState.AUTHENTICATED, result.state)

    def test_session_response_falls_back_to_august_header(self):
        common = self._build()
        result = common._authentication_from_session_response(
            "iid",
            {HEADER_AUGUST_ACCESS_TOKEN: "old"},
            {
                "expiresAt": _fmt(datetime.now(timezone.utc) + timedelta(days=1)),
                "vPassword": True,
                "vInstallId": True,
            },
        )
        self.assertEqual("old", result.access_token)

    def test_session_response_bad_password(self):
        common = self._build()
        result = common._authentication_from_session_response(
            "iid",
            {HEADER_AUGUST_ACCESS_TOKEN: "x"},
            {
                "expiresAt": _fmt(datetime.now(timezone.utc)),
                "vPassword": False,
                "vInstallId": True,
            },
        )
        self.assertEqual(AuthenticationState.BAD_PASSWORD, result.state)

    def test_session_response_requires_validation(self):
        common = self._build()
        result = common._authentication_from_session_response(
            "iid",
            {HEADER_AUGUST_ACCESS_TOKEN: "x"},
            {
                "expiresAt": _fmt(datetime.now(timezone.utc)),
                "vPassword": True,
                "vInstallId": False,
            },
        )
        self.assertEqual(AuthenticationState.REQUIRES_VALIDATION, result.state)

    def test_should_refresh_false_when_not_authenticated(self):
        common = self._build()
        common._authentication.state = AuthenticationState.REQUIRES_AUTHENTICATION
        self.assertFalse(common.should_refresh())

    def test_process_refreshed_access_token_with_exp(self):
        common = self._build()
        exp = int(
            (datetime.now(timezone.utc) + timedelta(days=14)).timestamp()
        )
        token = jwt.encode({"exp": exp}, "secret", algorithm="HS256")
        result = common._process_refreshed_access_token(token)
        self.assertEqual(token, result.access_token)
        # Stored as ISO format with trailing Z; parsed_expiration_time should
        # round-trip back to the same UTC timestamp.
        self.assertEqual(
            exp, int(result.parsed_expiration_time().timestamp())
        )

    def test_process_refreshed_access_token_missing_exp_warns(self):
        common = self._build()
        token = jwt.encode({"sub": "user"}, "secret", algorithm="HS256")
        with self.assertLogs("yalexs.authenticator_common", level="WARNING") as logs:
            result = common._process_refreshed_access_token(token)
        self.assertTrue(
            any("exp" in m for m in logs.output),
            f"expected exp warning, got: {logs.output}",
        )
        # Returned the existing authentication unchanged.
        self.assertEqual("old_token", result.access_token)
